# <center>NumPy

In [ ]:
 import numpy as np
np.set_printoptions(suppress=True)
#suppress the exponential values

### 1D array

In [2]:
a = np.array([10,20,30,50,60,0])
a

array([10, 20, 30, 50, 60,  0])

In [9]:
b = np.array([1,2,3,4,5,6,7,10,12,32,2,4,4,4,2])
b

array([ 1,  2,  3,  4,  5,  6,  7, 10, 12, 32,  2,  4,  4,  4,  2])

### Attributes of arrays

##### dtype

In [4]:
a.dtype

dtype('int32')

In [10]:
b.dtype

dtype('int32')

##### shape

In [5]:
a.shape

(6,)

In [11]:
b.shape

(15,)

##### n dim

In [31]:
# dimension of the array
a.ndim

1

In [12]:
b.ndim

1

##### size

In [7]:
#Total elements
a.size

6

In [13]:
b.size

15

### Indexing

In [8]:
a[0]

10

In [14]:
b[0]

1

In [15]:
a[-1]

0

In [16]:
b[-2]

4

In [17]:
a[2:4]

array([30, 50])

In [18]:
b[::-1]

array([ 2,  4,  4,  4,  2, 32, 12, 10,  7,  6,  5,  4,  3,  2,  1])

### Multidimensional array

In [19]:
a_2d = np.array([[10,20,30],[23,55,15]])

In [20]:
a_2d

array([[10, 20, 30],
       [23, 55, 15]])

In [21]:
a_2d.shape

(2, 3)

In [22]:
a_2d.ndim

2

In [23]:
a_2d.size

6

In [25]:
#Shows the first element in a_2d
a_2d[0]

array([10, 20, 30])

### Another type of multidimensional array

In [27]:
another_type_array = np.array([[[1,2,3,4]]])
another_type_array

array([[[1, 2, 3, 4]]])

In [28]:
another_type_array.shape

(1, 1, 4)

In [29]:
another_type_array.ndim

3

In [32]:
another_type_array.size

4

#### First element in the first arry

In [34]:
a_2d

array([[10, 20, 30],
       [23, 55, 15]])

In [33]:
a_2d[0][0]

10

#### Second element in the second array

In [35]:
a_2d[1][1]

55

#### Last element in the last array

In [36]:
a_2d[-1][-1]

15

#### Lets change its data type into float

In [45]:
a_2d = np.array([[10,20,30],[23,55,15]],dtype = float)

In [46]:
a_2d

array([[10., 20., 30.],
       [23., 55., 15.]])

### Lets create a bigger array

In [47]:
a_bigger = np.array([
    [
        [10,20,30,40],[8,8,2,1],[1,1,1,2]
    ],
    [
        [9,9,2,39],[1,2,3,3],[0,0,3,2]
    ],
    [
        [12,33,22,1],[22,1,22,2],[0,2,3,1]
    ]
    ],dtype=float)

In [69]:
#(elements in 1-D,elements in 2-D,elements in 3-D)
a_bigger.shape

(3, 3, 4)

In [49]:
a_bigger.ndim

3

In [50]:
a_bigger.size

36

In [51]:
a_bigger[2][2][3]

1.0

In [52]:
a_bigger[2][1][3]

2.0

In [54]:
a_bigger[1][1][2]

3.0

In [56]:
#Third element in the 2nd array
a_bigger[2][1]

array([22.,  1., 22.,  2.])

### Filling arrays

##### np.full

##### By using the full function for example, we fill an array of a certain shape with the same number. in this case we create a 3*5*4 matrix,which is filled with sevens

In [81]:
a_full = np.full((3,5,4),7)

In [82]:
a_full
#3 elements with matrices of 5 by 4 shape

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [60]:
a_full.ndim

3

### ZEROS AND ONES

##### For the cases that we want arrays full of zeros and ones , we even have specific functions

In [61]:
a_zeros = np.zeros((3,3))

In [62]:
a_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
b_ones = np.ones((2,3,4))

In [64]:
b_ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [65]:
b_ones.ndim

3

### EMPTY AND RANDOM

##### Other options would be to create an empty array or one that is filled with random numbers,For this, we use the respective function once again.

#### Empty

In [96]:
e = np.empty((4,4))

In [98]:
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### Random(shows values wirthin tyhe range 0 to 1)

In [76]:
b_random = np.random.random((2,2))

In [77]:
b_random

array([[[0.16916636, 0.12478747],
        [0.52476243, 0.92081669]]])

### RANGES

##### Instead of just filling arrays with the same values, we can fill create sequences of values by specifying the boundaries.For this , we can use two different functions, namely arrange and linspace

#### Arrange

##### Arguments are start-stop-step

In [74]:
#Third element step shows the incrementing option
a_arange = np.arange(10,50,3)
a_arange

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [85]:
b_arange = np.arange(10,50,5)
b_arange

array([10, 15, 20, 25, 30, 35, 40, 45])

### linspace

##### By using linspace we also create a list from a minimum value to a maximum value. But, instead of specifying the step-size, we specify the amount of values that we want to have in our list . They will all be spread evenly and have the same distance of their neighbors

##### start-stop-number of values

In [83]:
b_linspace = np.linspace(0,50,2)

In [90]:
# in linspace we can see the first and last element in the dataset 
b_linspace

array([ 0., 50.])

In [86]:
b_linspace.ndim

1

In [87]:
b_linspace.size

2

In [88]:
b_linspace1 = np.linspace(0,50,10)

In [89]:
b_linspace1

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [100]:
b_linspace1.size

10

In [101]:
b_linspace2 = np.linspace(0,50,30)

In [102]:
b_linspace2

array([ 0.        ,  1.72413793,  3.44827586,  5.17241379,  6.89655172,
        8.62068966, 10.34482759, 12.06896552, 13.79310345, 15.51724138,
       17.24137931, 18.96551724, 20.68965517, 22.4137931 , 24.13793103,
       25.86206897, 27.5862069 , 29.31034483, 31.03448276, 32.75862069,
       34.48275862, 36.20689655, 37.93103448, 39.65517241, 41.37931034,
       43.10344828, 44.82758621, 46.55172414, 48.27586207, 50.        ])

In [103]:
b_linspace2.size

30

##### showing linspace in int format

In [104]:
b_linspace3 = np.linspace(0,50,25,dtype=int)

In [105]:
b_linspace3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 50])

### np.exp(a)

##### Takes e to the power of each value

In [107]:
np.exp(1)
#shows the value of e

2.718281828459045

In [108]:
np.exp(2)

7.38905609893065